pool:
  name: myLaptop
  demands: npm

#Your build pipeline references an undefined variable named ‘Parameters.orchestratorConnection’. Create or edit the build pipeline for this YAML file, define the variable on the Variables tab. See https://go.microsoft.com/fwlink/?linkid=865972

steps:
- task: uipath.vsts-uipath-package.uipath-pack.UiPathPack@2
  displayName: 'UiPath Pack'
  inputs:
    versionType: AutoVersion
    projectJsonPath: HelloWorld
    outputType: Process
    orchestratorConnection: UiPathOrchConnection
    outputPath: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'

- task: "uipath.vsts-uipath-package.uipath-deploy.UiPathDeploy@2"
  displayName: 'UiPath Deploy'
   inputs:
    orchestratorConnection: UiPathOrchConnection
    packagesPath: '$(Build.ArtifactStagingDirectory)'
    folderName: default
    environments: Dev

- task: "PowerShell@2"
  inputs:
    targetType: "filePath"
    filePath: $(Build.SourcesDirectory)\Data\Workflow-Analyzer-CLI-Script
    arguments: > # Use this to avoid newline characters in multiline string
                -ProjectFilePath $(Build.SourcesDirectory)\project.json
                -ExecutableFilePath "C:\Users\prasa\AppData\Local\UiPath\app-21.4.4\UiPath.Studio.CommandLine.exe"
                -OutputFilePath '$(Pipeline.Workspace)\drop\Workflow-Analysis.json'
    workingDirectory: $(Build.SourcesDirectory)
           
